### ISSUE TITLE
Implement of Two-Step VHRED

### ISSUE THREAD

**Issue by YingyWang** [ZHAOTING/dialog-processing#5]
Hi, I found there were some comparative experiments between your VHRED lgm model and Two-Step VHRED model (Qiu et al. , 2019). Did u release the implement of the Two-Step VHRED model？I can't found in the folder “dialog-processing/src/model/response_gen_multi_response/”.
Looking forward to your reply! Thank u!

**Comment by ZHAOTING** [comment]
Hi @YingyWang , the two-step vhred corresponds to `src/response_gen_multi_response/vhred_multi_avg.py`. Please notice that it only implements the MBoW part, since I found details of other parts in the original paper not sufficient for re-implementation. And according to the reported results in the paper, the model with only MBoW (which is referred to as "Ours-First" in the paper) has presented decent performance.

**Comment by YingyWang** [comment]
> Hi @YingyWang , the two-step vhred corresponds to `src/response_gen_multi_response/vhred_multi_avg.py`. Please notice that it only implements the MBoW part, since I found details of other parts in the original paper not sufficient for re-implementation. And according to the reported results in the paper, the model with only MBoW (which is referred to as "Ours-First" in the paper) has presented decent performance.

Thanks a lot~~~~~~~
